additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: abu.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 4
      memoryMB: 32768
  replicas: 6
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 4
      memoryMB: 32768
  replicas: 3
metadata:
  creationTimestamp: null
  name: abuocpipi01
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.18.3.0/25
  networkType: OVNKubernetes
  serviceNetwork:
  - 10.136.0.0/16
platform:
  vsphere:
    apiVIPs:
    - 172.18.3.100
    cluster: CL-KO2-LAB-01
    datacenter: DC-KO2-LAB-01
    defaultDatastore: vsanDatastore
    ingressVIPs:
    - 172.18.3.110
    network: SEG-172.18.3.0_s25-Alessio_Buccoliero
    password: assembly.01
    username: Alessio.Buccoliero
    vCenter: ko2vcenter01lab.ko2.local
    folder: /DC-KO2-LAB-01/vm/ABU-Alessio_Buccoliero/IPI/
    resourcePool: /DC-KO2-LAB-01/host/CL-KO2-LAB-01/Resources/RP-Alessio_Buccoliero
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODI2Y2UxM2VjNzljNDk5Yzg4MjUwYzcyN2QxZWU0M2M6WklCTVk2QVRRTk1JUlVBUUdYWUI3V0VHVzRHRE9TTFdQQ0JNRDVHNjNHRzUyVEI2VE5MSDJNVU9SWTZXOU8yMQ==","email":"alessio.buccoliero@yahoo.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODI2Y2UxM2VjNzljNDk5Yzg4MjUwYzcyN2QxZWU0M2M6WklCTVk2QVRRTk1JUlVBUUdYWUI3V0VHVzRHRE9TTFdQQ0JNRDVHNjNHRzUyVEI2VE5MSDJNVU9SWTZXOU8yMQ==","email":"alessio.buccoliero@yahoo.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE4M2FjODAzLWNjZjMtNDMwOS05ZDAxLWMzOTIyN2YwOGQ2ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOekZqWVdFNU56RTJNR00wTlRBNFltRXlaVFk1TmpSa09EUTNabUUxTnlKOS5rSEJFcW9qeGlnOXQ1bm05anpPQTFzZUYwMkREakdHSEgwR1hncnhvaEV4M0FwS3g5WFBOQ3dQVFZQTDJ6cm9NVjFmZGVIa3diMVU0cEI5WkkycXVyNlVUaU8zZGlTUUxyekt3cmFZWmdvdFJ3ZkVkczB5eUJWbmxVMlRGcGl3YS1GcGRTYTlVbm05MmgyLXA1MEJuSDY3Yk1UZXhzZ2dqUTREYlpNWjVMSi1qQ00wbVV4WjFfeXg5d0xJejVIY3RtSFVfaXJrNURYOERqa1pKQ1FjMC14LTJncGJBNnBLMXBPWDdNNWtjUDliZDhXQkdHdGlnMDVGRzdWSmJUQXFiNVllbXpmQ1lvS3RyRjgzVkdQLTgzeGhBdWxXblZfbGJBd1pQZjAtU1ZJNXJESDRQNU1sWlVfZXJOdkFmeS1jVEFsM294eHRlVUI1YXZ1SjhSNVpyelU5cjB3NnRuNUVyWTIxbGg1ZmZLVzE3Vk4ycFhPckRJNEdNTFIxRXhYMG1kYnA5RFFsQWkxMDYxNkNWc0s2RUgzNUNMY2ZVN3RYRVNETjdKOFBIUkpmOWlWdDVxYklBVWQ1dmJhZUtLMjNPTW1taVJEcGl1WXJReUlqVm1jdlRJbDZDeUpjSVNOclNWOW1leEZfMVlMNU52dmtWb1YweVBTZ2s4NjJjdEN3RGx2SnFUbkxNWkJHSTBCeUg0dC1ySEVtMmZhb21kTGhwcVliTHN2azRlQlllS1kxVmFXd2JXdk9UQ2tRcEFicHJfc1lQblk3N190TkV4WEgyVUFFbnBYMVhPRnhTX0NvSVQ4dlFGWG1GTWwtTXg3YldnVzh6bWFHT3VUODBDaTBxREtNbDFBYTFEemVlcEh2dmJiNkhTMEN6ZmkzcVFxekhkcXNJU1pCZXQxaw==","email":"alessio.buccoliero@yahoo.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE4M2FjODAzLWNjZjMtNDMwOS05ZDAxLWMzOTIyN2YwOGQ2ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOekZqWVdFNU56RTJNR00wTlRBNFltRXlaVFk1TmpSa09EUTNabUUxTnlKOS5rSEJFcW9qeGlnOXQ1bm05anpPQTFzZUYwMkREakdHSEgwR1hncnhvaEV4M0FwS3g5WFBOQ3dQVFZQTDJ6cm9NVjFmZGVIa3diMVU0cEI5WkkycXVyNlVUaU8zZGlTUUxyekt3cmFZWmdvdFJ3ZkVkczB5eUJWbmxVMlRGcGl3YS1GcGRTYTlVbm05MmgyLXA1MEJuSDY3Yk1UZXhzZ2dqUTREYlpNWjVMSi1qQ00wbVV4WjFfeXg5d0xJejVIY3RtSFVfaXJrNURYOERqa1pKQ1FjMC14LTJncGJBNnBLMXBPWDdNNWtjUDliZDhXQkdHdGlnMDVGRzdWSmJUQXFiNVllbXpmQ1lvS3RyRjgzVkdQLTgzeGhBdWxXblZfbGJBd1pQZjAtU1ZJNXJESDRQNU1sWlVfZXJOdkFmeS1jVEFsM294eHRlVUI1YXZ1SjhSNVpyelU5cjB3NnRuNUVyWTIxbGg1ZmZLVzE3Vk4ycFhPckRJNEdNTFIxRXhYMG1kYnA5RFFsQWkxMDYxNkNWc0s2RUgzNUNMY2ZVN3RYRVNETjdKOFBIUkpmOWlWdDVxYklBVWQ1dmJhZUtLMjNPTW1taVJEcGl1WXJReUlqVm1jdlRJbDZDeUpjSVNOclNWOW1leEZfMVlMNU52dmtWb1YweVBTZ2s4NjJjdEN3RGx2SnFUbkxNWkJHSTBCeUg0dC1ySEVtMmZhb21kTGhwcVliTHN2azRlQlllS1kxVmFXd2JXdk9UQ2tRcEFicHJfc1lQblk3N190TkV4WEgyVUFFbnBYMVhPRnhTX0NvSVQ4dlFGWG1GTWwtTXg3YldnVzh6bWFHT3VUODBDaTBxREtNbDFBYTFEemVlcEh2dmJiNkhTMEN6ZmkzcVFxekhkcXNJU1pCZXQxaw==","email":"alessio.buccoliero@yahoo.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTQsA5lfHQmu82t5qHiw8pfjwqoS/WTAcukTWxHiLD2CFcUTYYLILvNjLz9LtAnLNvxhJ26/0NRGzpjF4jUs6YDGdqWeI1dMuLw6xRFMINZeHQ4g2HoR9+SQHQOIQT/xyg/93q1K+1mXIJXn9X8umdItvghqk1UcQIV+/xyGFUO/CvqZZiB6YSI/vDdq3SavtT+X8Da+2NF0tDNdmt2SVSqYn/varQRo8ZJb3MNUQtIFJsh+8h3IFakTBY7KnG8/pxb8IcLnUNkbarFbfnC0Tww8+AcDHoptm/OCTBll3bGpM3OwASDl6YHDhWSFfW4Q+WUcab8dvjieA2AaiSI0bsGsjCosZ23l30icY0ySsivs5YsEAqi8QYwm2bouto4+N4VW0ujc+UYUFZL3LDBADC2r2sJ5PWC/zTfgh84iMBIOREoSnRT+PD7eOLFh8cixl47D/aLzwU3rdXwfDkZw/3byUzdjxucYP/Q3q8QKzz4y5kn1I2Vk4bm0ukAmed+Vc= user@os-ipi-bh01
