additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: abu.local
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 4
      memoryMB: 16384
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 4
      memoryMB: 16384
  replicas: 3
metadata:
  creationTimestamp: null
  name: abuocpupi02
networking:
  clusterNetwork:
  - cidr: 10.132.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.18.3.128/25
  networkType: OVNKubernetes
  serviceNetwork:
  - 10.137.0.0/16
platform:
  vsphere:
    diskType: thin
    apiVIPs:
    - 172.18.3.200
    cluster: CL-KO2-LAB-01
    datacenter: DC-KO2-LAB-01
    defaultDatastore: vsanDatastore
    ingressVIPs:
    - 172.18.3.210
    network: SEG-172.18.3.128_s25-Alessio_Buccoliero
    resourcePool: /DC-KO2-LAB-01/host/CL-KO2-LAB-01/Resources/RP-Alessio_Buccoliero
    folder: /DC-KO2-LAB-01/vm/ABU-AlessioBuccoliero/UPI/
    password: assembly.01
    username: Alessio.Buccoliero
    vCenter: ko2vcenter01lab.ko2.local
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODI2Y2UxM2VjNzljNDk5Yzg4MjUwYzcyN2QxZWU0M2M6WklCTVk2QVRRTk1JUlVBUUdYWUI3V0VHVzRHRE9TTFdQQ0JNRDVHNjNHRzUyVEI2VE5MSDJNVU9SWTZXOU8yMQ==","email":"alessio.buccoliero@yahoo.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODI2Y2UxM2VjNzljNDk5Yzg4MjUwYzcyN2QxZWU0M2M6WklCTVk2QVRRTk1JUlVBUUdYWUI3V0VHVzRHRE9TTFdQQ0JNRDVHNjNHRzUyVEI2VE5MSDJNVU9SWTZXOU8yMQ==","email":"alessio.buccoliero@yahoo.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE4M2FjODAzLWNjZjMtNDMwOS05ZDAxLWMzOTIyN2YwOGQ2ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOekZqWVdFNU56RTJNR00wTlRBNFltRXlaVFk1TmpSa09EUTNabUUxTnlKOS5rSEJFcW9qeGlnOXQ1bm05anpPQTFzZUYwMkREakdHSEgwR1hncnhvaEV4M0FwS3g5WFBOQ3dQVFZQTDJ6cm9NVjFmZGVIa3diMVU0cEI5WkkycXVyNlVUaU8zZGlTUUxyekt3cmFZWmdvdFJ3ZkVkczB5eUJWbmxVMlRGcGl3YS1GcGRTYTlVbm05MmgyLXA1MEJuSDY3Yk1UZXhzZ2dqUTREYlpNWjVMSi1qQ00wbVV4WjFfeXg5d0xJejVIY3RtSFVfaXJrNURYOERqa1pKQ1FjMC14LTJncGJBNnBLMXBPWDdNNWtjUDliZDhXQkdHdGlnMDVGRzdWSmJUQXFiNVllbXpmQ1lvS3RyRjgzVkdQLTgzeGhBdWxXblZfbGJBd1pQZjAtU1ZJNXJESDRQNU1sWlVfZXJOdkFmeS1jVEFsM294eHRlVUI1YXZ1SjhSNVpyelU5cjB3NnRuNUVyWTIxbGg1ZmZLVzE3Vk4ycFhPckRJNEdNTFIxRXhYMG1kYnA5RFFsQWkxMDYxNkNWc0s2RUgzNUNMY2ZVN3RYRVNETjdKOFBIUkpmOWlWdDVxYklBVWQ1dmJhZUtLMjNPTW1taVJEcGl1WXJReUlqVm1jdlRJbDZDeUpjSVNOclNWOW1leEZfMVlMNU52dmtWb1YweVBTZ2s4NjJjdEN3RGx2SnFUbkxNWkJHSTBCeUg0dC1ySEVtMmZhb21kTGhwcVliTHN2azRlQlllS1kxVmFXd2JXdk9UQ2tRcEFicHJfc1lQblk3N190TkV4WEgyVUFFbnBYMVhPRnhTX0NvSVQ4dlFGWG1GTWwtTXg3YldnVzh6bWFHT3VUODBDaTBxREtNbDFBYTFEemVlcEh2dmJiNkhTMEN6ZmkzcVFxekhkcXNJU1pCZXQxaw==","email":"alessio.buccoliero@yahoo.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE4M2FjODAzLWNjZjMtNDMwOS05ZDAxLWMzOTIyN2YwOGQ2ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTBOekZqWVdFNU56RTJNR00wTlRBNFltRXlaVFk1TmpSa09EUTNabUUxTnlKOS5rSEJFcW9qeGlnOXQ1bm05anpPQTFzZUYwMkREakdHSEgwR1hncnhvaEV4M0FwS3g5WFBOQ3dQVFZQTDJ6cm9NVjFmZGVIa3diMVU0cEI5WkkycXVyNlVUaU8zZGlTUUxyekt3cmFZWmdvdFJ3ZkVkczB5eUJWbmxVMlRGcGl3YS1GcGRTYTlVbm05MmgyLXA1MEJuSDY3Yk1UZXhzZ2dqUTREYlpNWjVMSi1qQ00wbVV4WjFfeXg5d0xJejVIY3RtSFVfaXJrNURYOERqa1pKQ1FjMC14LTJncGJBNnBLMXBPWDdNNWtjUDliZDhXQkdHdGlnMDVGRzdWSmJUQXFiNVllbXpmQ1lvS3RyRjgzVkdQLTgzeGhBdWxXblZfbGJBd1pQZjAtU1ZJNXJESDRQNU1sWlVfZXJOdkFmeS1jVEFsM294eHRlVUI1YXZ1SjhSNVpyelU5cjB3NnRuNUVyWTIxbGg1ZmZLVzE3Vk4ycFhPckRJNEdNTFIxRXhYMG1kYnA5RFFsQWkxMDYxNkNWc0s2RUgzNUNMY2ZVN3RYRVNETjdKOFBIUkpmOWlWdDVxYklBVWQ1dmJhZUtLMjNPTW1taVJEcGl1WXJReUlqVm1jdlRJbDZDeUpjSVNOclNWOW1leEZfMVlMNU52dmtWb1YweVBTZ2s4NjJjdEN3RGx2SnFUbkxNWkJHSTBCeUg0dC1ySEVtMmZhb21kTGhwcVliTHN2azRlQlllS1kxVmFXd2JXdk9UQ2tRcEFicHJfc1lQblk3N190TkV4WEgyVUFFbnBYMVhPRnhTX0NvSVQ4dlFGWG1GTWwtTXg3YldnVzh6bWFHT3VUODBDaTBxREtNbDFBYTFEemVlcEh2dmJiNkhTMEN6ZmkzcVFxekhkcXNJU1pCZXQxaw==","email":"alessio.buccoliero@yahoo.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbwrVsmwkq9pjLZrD1HA9ulUgnBRFpg42hWfnIpmIIInyHG1LGlv9QJilko45btky2KHGyeT68GLCGS82rQlkc1i6YLOsc2zuoHVzBuzlQvHf9p77CRfAgQDMgpfB+wy+L8Hf8796djoUNEbLGZHmbCq97vahsm9wFBs35CrYjN4NTG7ntNYZkGNtuDvxC17KU0qlTvwa/wJ8KrQQ4UlYeBBDL/eOd+QbCw9NQJXppE6gMBgttvmOoBAi1FbiDztraeF9gbKzfdo13Yf4MtUr9usgCTlne9J2twTKMj/fEqZtUEkVm33LrNdbpqq8cfeOu0jwSU2JLCgPxgQWbbDhbqcOUqOLyXrKVQfpRPCH6sCwqsrxr+tjNLv8bn7MIZEO7y4CynZVhgntGkGE4XpZhsQDk6PM1+y/+ff0Ck22MUosz7+jEV2Bp7EnhZSzs8WA3sXIlCIng2vIGU6IPrpMjzGpWt927wfb3H4Ut68Yj6O8ZwsGdYuwho5mqlUwQXqE= user@os-upi-bh01
